Repository exaile/exaile, pull requests merged in 2018-03, with the labels that each got.

#486 smart playlists: add 'contains word' operation
  xl/playlist.py
  xlgui/widgets/smart_playlist_editor.py
Labels: Type: enhancement

#490 GroupTagger: Force line break in title/artist labels
  plugins/grouptagger/gt_widgets.py
Labels: Easy, GTK3/GST1.x, GUI, Type: bug

#488 playlist: restore view when filtering
  xlgui/guiutil.py
  xlgui/widgets/playlist.py
Labels: Type: enhancement

#494 Cleanup: Unused imports and documentation
  doc/conf.py
  doc/xlgui/icons.rst
  xlgui/panel/flatplaylist.py
  xlgui/panel/radio.py
  xlgui/widgets/common.py
Labels: Easy, Python code quality, Type: enhancement
